#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG=/usr/sbin/linkease-lite
LOCAL_API=/var/run/linkeaselite.sock

read_config() {
	section="$1"
	config_get_bool enabled "$section" enabled 1
	config_get port "$section" port 8897
	config_get_bool allowPublic "$section" allowPublic 0
}

start_service() {
	config_load linkeaselite
	config_foreach read_config linkeaselite
	[ "$enabled" = "1" ] || return 1
	[ -x "$PROG" ] || return 1

	rm -f "$LOCAL_API"

	procd_open_instance linkeaselite
	procd_set_param limits nofile="65535 65535"
	procd_set_param command "$PROG"
	procd_append_param command --deviceAddr ":$port" --localApi "$LOCAL_API"
	[ "$allowPublic" = "1" ] && procd_append_param command --allowPublic
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "linkeaselite"
}
